name: Scanoss Java Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_test:
    name: Build and test java code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Build
        run: mvn --no-transfer-progress clean compile

      - name: Unit Test
        run: mvn --no-transfer-progress test


  # Upload all the jars and binaries  a GH Release
  create_release:
    if: success()
    needs: [ build_jars, build_native ]
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Cached artifacts
        uses: actions/download-artifact@v3
        with:
          name: scanoss-jars
          path: target

      - name: List Packages
        continue-on-error: true
        run: |
          ls -la target/

      # Only create a release if we have a tagged push
      - name: Release ${{ github.ref_type }} - ${{ github.ref_name }}
        if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            target/*
            scanoss-cli.sh